# Generated by Django 5.0.3 on 2024-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
