# Generated by Django 5.0.3 on 2024-04-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
        ('new', '0002_rename_news_new_alter_new_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
    ]
