# Generated by Django 5.0.3 on 2024-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_new_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
