# Generated by Django 5.0.3 on 2024-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_date_of_birth_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sername',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
