# Generated by Django 5.0.3 on 2024-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_sername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sername',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
