# Generated by Django 5.0.3 on 2024-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
