# Generated by Django 5.0.3 on 2024-04-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_course_students_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Course',
            new_name='courses',
        ),
    ]
