# Generated by Django 5.0.3 on 2024-04-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_teacher_courses_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='account.student', verbose_name="Teacher's students"),
        ),
    ]
