# Generated by Django 5.0.3 on 2024-03-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'تمرین', 'verbose_name_plural': 'تمرینات'},
        ),
    ]
