# Generated by Django 5.0.3 on 2024-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise/exercise_files/'),
        ),
    ]
