# Generated by Django 5.0.3 on 2024-04-15 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_exercise_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 5, 56, 13, 446792, tzinfo=datetime.timezone.utc)),
        ),
    ]
