# Generated by Django 5.0.3 on 2024-04-20 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 7, 14, 36, 597340, tzinfo=datetime.timezone.utc)),
        ),
    ]
