# Generated by Django 5.0.3 on 2024-04-26 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 56, 14, 691961, tzinfo=datetime.timezone.utc)),
        ),
    ]
