# Generated by Django 5.0.3 on 2024-04-27 06:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_teacher_assigned_student'),
        ('exercise', '0017_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 6, 25, 21, 423326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ExerciseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='exercise/response_files/')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exercise.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name': 'Exercise Response',
                'verbose_name_plural': 'Exercise Responses',
            },
        ),
    ]
