# Generated by Django 5.0.3 on 2024-04-27 07:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_teacher_assigned_student'),
        ('exercise', '0018_alter_exercise_options_alter_exercise_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_exercise', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 7, 28, 30, 7550, tzinfo=datetime.timezone.utc)),
        ),
    ]
