# Generated by Django 5.0.3 on 2024-04-27 08:25

import datetime
import exercise.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0019_exerciseresponse_created_by_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 8, 25, 25, 158789, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='exerciseresponse',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise/response_files/', validators=[exercise.validators.validate_zip_or_pdf]),
        ),
    ]
