# Generated by Django 5.0.3 on 2024-04-27 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_alter_exercise_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 16, 41, 26, 392432, tzinfo=datetime.timezone.utc)),
        ),
    ]
