# Generated by Django 5.0.3 on 2024-04-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 8, 59, 14, 990906, tzinfo=datetime.timezone.utc)),
        ),
    ]
