# Generated by Django 5.0.3 on 2024-04-28 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0022_alter_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 9, 0, 46, 236015, tzinfo=datetime.timezone.utc)),
        ),
    ]
